// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhgB926Ageqr3JPA6U6toSG4o-lyyCirg',
    appId: '1:769522994941:web:a839a4a4ff3e929c3ef894',
    messagingSenderId: '769522994941',
    projectId: 'getting-together-with-friends',
    authDomain: 'getting-together-with-friends.firebaseapp.com',
    storageBucket: 'getting-together-with-friends.firebasestorage.app',
    measurementId: 'G-4KSE3YPXY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDaxUe7deO0fczE0itfGBhrz1YgkIQdjA',
    appId: '1:769522994941:android:c622451d320fee5c3ef894',
    messagingSenderId: '769522994941',
    projectId: 'getting-together-with-friends',
    storageBucket: 'getting-together-with-friends.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyH3_ANvcN-DTjJf4Pdr18OpRv9wP6dOs',
    appId: '1:769522994941:ios:309faceaa56b0ca63ef894',
    messagingSenderId: '769522994941',
    projectId: 'getting-together-with-friends',
    storageBucket: 'getting-together-with-friends.firebasestorage.app',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyH3_ANvcN-DTjJf4Pdr18OpRv9wP6dOs',
    appId: '1:769522994941:ios:309faceaa56b0ca63ef894',
    messagingSenderId: '769522994941',
    projectId: 'getting-together-with-friends',
    storageBucket: 'getting-together-with-friends.firebasestorage.app',
    iosBundleId: 'com.example.travel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhgB926Ageqr3JPA6U6toSG4o-lyyCirg',
    appId: '1:769522994941:web:e57f18f17ea9ebd43ef894',
    messagingSenderId: '769522994941',
    projectId: 'getting-together-with-friends',
    authDomain: 'getting-together-with-friends.firebaseapp.com',
    storageBucket: 'getting-together-with-friends.firebasestorage.app',
    measurementId: 'G-461QJV8EQT',
  );

}